#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#fix: .husky/commit-msg: line 4: npx: command not found
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npx --no -- commitlint --edit ""
